spring.application.name=backend
server.port=9090
spring.datasource.url=jdbc:mariadb://localhost:3306/yongwchoi26
spring.datasource.username=root
spring.datasource.password=welcome
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.example.iocdi.domain
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.com.example.iocdi.mapper=debug